### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Philex5** [ykamikawa/PSPNet#1]
I used your model train my data but got a error:

ValueError: Error when checking target: expected activation_51 to have shape (None, 230400, 2) but got array with shape (998, 480, 480)

Can you help me solve it ?

**Comment by amlarraz** [comment]
Hey @philex5, I just solved this problem, if you use your own data generator, you must reshape the mask before add to the list with the batch: 

mask=mask.reshape(inputdim[0]*inputdim[1], n_labels)

You can see this transformation in the function "catelab" in generator.py (https://github.com/ykamikawa/PSPNet/blob/master/generator.py)
